version: '3.8'

services:
  mongodb_products:
    image: mongo
    container_name: mongodb_products
    restart: always
    ports:
      - "27017:27017"

  postgresql_orders:
    image: postgres
    container_name: postgresql_orders
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
    command: start-dev
    ports:
      - "8181:8080"

#  docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:25.0.0 start-dev