eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service #lb:// gives load balancing
          predicates:
            - Path=/api/products
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory
        - id: discovery-server
          uri: http://localhost:8761 #imposible to load balancing
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/ #removing from the path /eureka/web
#       for some styles we need also have address. sequence is important!
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm

logging:
  level:
    org.springframework.cloud:
        gateway: INFO
        gateway.route.RouteDefinitionLocator: TRACE
