spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

server:
  port: 0 #peek one random free port
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka