spring:
  application:
    name: product-service

  zipkin:
    base-url: http://localhost:9411

  data:
    mongodb:
      uri: mongodb://localhost:27017/test

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
server:
  port: 0 #peek one random free port